### PR TITLE
add sidecars explanation to readme

### PR DESCRIPTION
**Pull request by Islast**
I have tried here to illuminate how the sidecar matching works, since that was what really confused me when I started with this tool.
Tell me what you think :sunny:

### CODE REVIEW

**Comment by neurolabusc** [comment]
dcm2niix will use the BIDS tag `PhaseEncodingDirection` to report the direction and polarity, if known. For example, `"PhaseEncodingDirection": "j-",`. Be aware that current Philips software does not encode [phase encoding polarity]( https://github.com/rordenlab/dcm2niix/issues/151). @cbedetti  can describe the best way to encode this heuristic into Dcm2Bids.

**Comment by Islast** [comment]
Hi,
@neurolabusc I'm so sorry, I'm not sure I understand the comment. Did you want me to add this information to the readme in this PR?

**Comment by neurolabusc** [comment]
No, your PR looks nice. Please ignore my prior comment.

**Comment by Islast** [comment]
@cbedetti Just a reminder that this is still here. I won't mind if you choose to close without merging :smile:

**Pull request merged**
